// ════════════════════════════════════════
//  STATE
// ════════════════════════════════════════
const S = {
  companyName: "",
  serviceName: "",
  effectiveDate: "",
  collectNoConsent: [],
  collectConsent: [],
  collectOther: [],
  collectAuto: [],
  child: "no",
  childItems: "",
  childMethod: "",
  retention: { contract: true, dispute: true, ad: true, log: true },
  customRetentionLegal: [],
  customRetentionOther: [],
  destroy: { electronic: true, paper: true },
  thirdParty: "no",
  tpConsent: [],
  tpLegal: [],
  delegate: "no",
  dlItems: [],
  dlSubItems: [],
  overseas: "no",
  otItems: [],
  otRefuseDisadvantage: "",
  otRefuseMethod: "",
  security: {
    s_plan: true,
    s_edu: true,
    s_org: false,
    s_access: true,
    s_encrypt: true,
    s_sec: true,
    s_log: false,
    s_vuln: false,
    s_phys: true,
    s_media: false,
    s_isms: false,
    s_isms_cert: false,
    s_mgmt_extra: [],
    s_tech_extra: [],
    s_phys_extra: [],
    s_cert_extra: [],
  },
  cookie: "yes",
  browser: {
    b_chrome: true,
    b_edge: true,
    b_chrome_m: false,
    b_safari: false,
    b_samsung: false,
  },
  cookie3rdParty: "no",
  cookieExtDevices: [],
  behavioral: "no",
  bhPurpose: "",
  bhTool: "쿠키",
  bhIdentifyMode: "nonidentify",
  bhItems: [],
  bhProvide: "no",
  bhTpItems: [],
  bhExtCollect: "no",
  bhAutoDevices: [],
  bhFlags: { bh_nosensitive: true, bh_nochild: true, bh_mobile: true },
  bhSensitivePurpose: "최적화된 맞춤형 서비스 및 혜택, 온라인 맞춤형 광고 등",
  bhChildAction: "아동에게 맞춤형 광고를 제공",
  bhMobileAction: "맞춤형 광고를 위하여 광고식별자를 수집·이용",
  bhMobileAdType: "맞춤형 광고",
  bhBrowsers: { bh_chrome: true, bh_edge: true },
  bhContactDept: "",
  bhContactPerson: "",
  bhContactPhone: "",
  bhContactEmail: "",
  rights: {
    r_written: true,
    r_phone: true,
    r_email: true,
    r_fax: false,
    r_web: false,
  },
  rightsOnline: "no",
  rightsWebPath: "",
  rightsAppPath: "",
  rightsActions: { ra_view: true, ra_edit: true, ra_delete: true, ra_suspend: true, ra_withdraw: true },
  rightsInquiryPath: "문의하기",
  mydata: "no",
  rightsDeptName: "",
  rightsDeptPhone: "",
  rightsDeptEmail: "",
  rightsDeptFax: "",
  cpoName: "",
  cpoTitle: "",
  cpoPhone: "",
  cpoEmail: "",
  depts: [{ name: "", phone: "", email: "" }],
  agency: { ag_kopico: true, ag_kisa: true, ag_spo: true, ag_police: true },
  addUsage: "no",
  addUsageRows: [],
  addUsageCriteria: { c1Var: "서비스 제공", c4Var: "안심번호 사용" },
  sensitive: "no",
  sensitiveRows: [],
  pseudonym: "no",
  pseudonymRows: [],
  pseudonymProvide: "no",
  pseudonymProvideRows: [],
  autoDecision: "no",
  adPurpose: "",
  adSubjectScope: "",
  adInfoRows: [],
  adProcedure: "",
  adSensitive: "no",
  adSensitiveDetail: "",
  adContactDept: "",
  adContactPhone: "",
  adContactEmail: "",
  adContactAddr: "",
  domAgent: "no",
  daName: "",
  daPhone: "",
  daAddr: "",
  daEmail: "",
  prevPolicies: [],
};
